import release from '@/public/data/latest.json';
import { METROS, type buildDecisionAnalysis } from './decision-analysis';

export function buildExecutiveEvidence(analysis: ReturnType<typeof buildDecisionAnalysis>) {
  const material = analysis.materials[0];
  const labour = [...analysis.labourRows].filter((row) => row.vacancies_per_1_000_2021_employed !== null).sort((a, b) => (b.vacancies_per_1_000_2021_employed ?? 0) - (a.vacancies_per_1_000_2021_employed ?? 0))[0];
  const signals = [
    { id: 'materials', label: 'Materials', value: material ? `${material.year_over_year_percent_change > 0 ? '+' : ''}${material.year_over_year_percent_change.toFixed(1)}%` : 'Unavailable', unit: 'observed YoY change', scope: METROS[analysis.metroId], period: material?.period_end ?? 'Observation unavailable', status: material ? 'Derived from observed indices' : 'Missing observation', detail: material ? `${material.component.replaceAll('_', ' ')} · ${analysis.asset.proxy}` : 'No matching component series.', supports: 'Identify components to market-test in the selected building-price proxy.', limitation: analysis.asset.profileNote, next: 'Obtain project-specific quantities and current supplier quotes before changing the estimate.', sourceIds: material ? [material.source_id] : [] },
    { id: 'labour', label: 'Labour', value: labour?.vacancies_per_1_000_2021_employed?.toFixed(1) ?? 'Unavailable', unit: 'vacancies / 1,000 employed in 2021', scope: 'Alberta · not a local capacity estimate', period: `Vacancies ${analysis.labourDates.vacancy} · workforce ${analysis.labourDates.workforce}`, status: labour ? 'Mixed-vintage diagnostic' : 'Missing or suppressed components', detail: labour ? labour.trade_node_id.replaceAll('_', ' ') : 'No complete relevant trade diagnostic.', supports: 'Prioritize trade-capacity conversations for this asset’s declared graph paths.', limitation: 'Not a vacancy rate or a count of available workers. Suppressed components remain missing; the 2021 denominator is not current workforce capacity.', next: 'Confirm contractor availability, crew plans and bid coverage in the project market.', sourceIds: [release.labour_pressure.vacancy_source_id, release.labour_pressure.workforce_source_id] },
    { id: 'power', label: 'Power', value: `${analysis.powerEvidence.requested_load.latest_requested_load_mw / 1000} GW`, unit: 'requested load · not connected', scope: 'Alberta · AESO application pipeline', period: analysis.powerEvidence.requested_load.latest_application_period, status: 'Reported connection requests', detail: 'Data-centre requested load', supports: 'Flag the need to coordinate utility interfaces and connection assumptions.', limitation: 'Requests are not contracts, realized demand or a transmission-build requirement. No project-specific connection study is included.', next: 'Request utility confirmation of connection timing and site-specific system requirements.', sourceIds: ['AESO_DATA_CENTRE_UPDATE_2025_09'] },
    { id: 'projects', label: 'Public projects', value: String(analysis.concurrentProjectCount), unit: 'same-class overlapping records', scope: 'Alberta · not filtered to the selected city', period: `Inventory snapshot ${release.public_project_exposure.as_of_date}`, status: 'Screened public records', detail: `${analysis.asset.label} · ${analysis.startYear}–${analysis.endYear}`, supports: 'Screen potentially concurrent public-project activity within the delivery window.', limitation: 'Incomplete schedules are excluded. Zero matches does not mean no competition; records are not realized spending or confirmed bids.', next: 'Verify procurement dates and delivery schedules with project owners.', sourceIds: [release.public_project_exposure.source_id] },
  ];
  return signals.map((signal) => ({ ...signal, role: 'Context only' as const, sources: signal.sourceIds.map((id) => ({ id, record: release.sources.find((source) => source.source_id === id) ?? null })) }));
}
